### ISSUE TITLE
remove plane fit hardcoded path

### ISSUE THREAD

**Issue by mvdm** [vandermeerlab/EC_Naris#4]
AMPX_plane_count_hist.m contains some hardcoded paths (`G:\Naris\Naris_stats_plane.txt`, line 41), should be replaced with reference to global params struct or some such (see also #2)

Also, that line and subsequent code seem to assume that file already exists; where is it created?

**Comment by ecarmichael** [comment]
fixed.  uses global PARAMS.stats_dir
