### ISSUE TITLE
match up session names used across different code segments

### ISSUE THREAD

**Issue by mvdm** [vandermeerlab/EC_Naris#5]
Naris_paper_sandbox.m does not include `R045_2014_04_15` in the session list, but AMPX_Naris_fig_1_example (line 133) refers to it.

**Comment by mvdm** [comment]
same thing in AMPX_Naris_fig_2_task (line 49)

**Comment by ecarmichael** [comment]
Looking at my Naris sandbox it has R045-2014-04-15 not -18.  18 was never par of my set.  I am not sure how it was part of that script

**Comment by mvdm** [comment]
OK, so the fix is to push a version of Naris_paper_sandbox.m with the correct filenames -- do you want to rename that file to something more polished before we promote it to the official paper code?

**Comment by ecarmichael** [comment]
Yes.  I am okay with any changes that make my code more polished
