### ISSUE TITLE
remove hardcoded paths in naris analysis workflow

### ISSUE THREAD

**Issue by mvdm** [vandermeerlab/EC_Naris#9]
Naris_gamma_count_mod (line 116) contains an output path, should be set in global var

in addition, what happens if the file being loaded doesn't exist yet? should be a statement detecting and handling that case.

**Comment by ecarmichael** [comment]
fixed.  Uses Global PARAMS.naris_gamma_inter_dir .  If this does not exist it makes an empty 'naris_gamma' to be filled and subsequently saved.
